### ISSUE TITLE
TODO finished v0.1.29

### ISSUE THREAD

**Issue by jonaprieto** [apkgbot/agda-pkg#23]
-  [x] Index some popular libraries 
-  [x] install dependencies if the user approves that.
-  [x] Read relevant environment variables like AGDA_DIR
-  [x] Offer the chance to generate pkg file and normal files
-  [x] README document the alternative format file .agda-pkg
-  [x] Improve help messages
-  [x] Specify the version of agda to install packages
-  [x] Update command
-  [x] Split the install command in index/local/urls/gits
-  [x] Install from the git repositories with version as tag (commit)

   -  [X] Create a temporal directory
   -  [X] Install as a local package
   -  [x] Mark the package as git repository

-  [x] Install from the git repositories using info from the index

   -  [X] Check the index, the file url
   -  [X] Check the version to exists (git tag..)
   -  [X] Install as a git repository
   -  [X] git checkout on the package source with the tag or commit

-  [x] Travis at least on OSX
-  [x] Pip package
